DROP TABLE IF EXISTS dm.dm_f101_round_f;
CREATE TABLE dm.dm_f101_round_f(
	 FROM_DATE				DATE
	,TO_DATE				DATE
	,CHAPTER				VARCHAR(1)
	,LEDGER_ACCOUNT			VARCHAR(5)
	,CHARACTERISTIC			VARCHAR(1)
	,BALANCE_IN_RUB			NUMERIC(23,8)
	,R_BALANCE_IN_RUB		NUMERIC(23,8)
	,BALANCE_IN_VAL			NUMERIC(23,8)
	,R_BALANCE_IN_VAL		NUMERIC(23,8)
	,BALANCE_IN_TOTAL		NUMERIC(23,8)
	,R_BALANCE_IN_TOTAL		NUMERIC(23,8)
	,TURN_DEB_RUB			NUMERIC(23,8)
	,R_TURN_DEB_RUB			NUMERIC(23,8)
	,TURN_DEB_VAL			NUMERIC(23,8)
	,R_TURN_DEB_VAL			NUMERIC(23,8)
	,TURN_DEB_TOTAL			NUMERIC(23,8)
	,R_TURN_DEB_TOTAL		NUMERIC(23,8)
	,TURN_CRE_RUB			NUMERIC(23,8)
	,R_TURN_CRE_RUB			NUMERIC(23,8)
	,TURN_CRE_VAL			NUMERIC(23,8)
	,R_TURN_CRE_VAL			NUMERIC(23,8)
	,TURN_CRE_TOTAL			NUMERIC(23,8)
	,R_TURN_CRE_TOTAL		NUMERIC(23,8)
	,BALANCE_OUT_RUB		NUMERIC(23,8)
	,R_BALANCE_OUT_RUB		NUMERIC(23,8)
	,BALANCE_OUT_VAL		NUMERIC(23,8)
	,R_BALANCE_OUT_VAL		NUMERIC(23,8)
	,BALANCE_OUT_TOTAL		NUMERIC(23,8)
	,R_BALANCE_OUT_TOTAL	NUMERIC(23,8)
);

--select * from dm.dm_f101_round_f;